#!/usr/bin/env bash
# setting up Nginx on a remote server with a bash script

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
